name: exercicio_layout
description: "A new Flutter project."
publish_to: 'none' # Não publicar este projeto no pub.dev
version: 0.1.0+1

environment:
  sdk: ">=3.7.0 <4.0.0" # Definindo a versão do SDK Flutter compatível

dependencies:
  flutter:
    sdk: flutter

  # Dependências adicionais (se precisar de pacotes extras)
  # Adicionar pacotes conforme necessário, por exemplo:
  # http: ^0.14.0
  # firebase_core: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets e fontes (se necessário)
  # assets:
  #   - assets/images/
  #   - assets/icons/
